# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pawan Ponders # the title of the website (e.g.: name of the individual)
description: >- # this means to ignore newlines until "baseurl:"
  Bhautiki for Jekyll. See About.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pawanmsr.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Pawan H Mishra
  email: pawanmsr@outlook.com
  # supply sha256sum of email for gravatar
  # gravatar: '?d=robohash&f=y&s=200'
  picture: /assets/img/profile.png
  url:
  socials:
    twitter:
      username: pawanmsr
    github:
      username: pawanmsr
    linkedin:
      username: pawanmsr
    facebook:
      username:
    instagram:
      username:
    twitch:
      username:
    goodreads:
      username: pawanmsr
    youtube:
      username:

# Build settings
# theme: jekyll-bhautiki
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-include-cache
  - jekyll-sitemap # requires base hostname and protocol for site; see url above

# Analytics
analytics:
  google:

# Language
lang: eng
# TODO: learn the language and then add language support.
# langs = [eng, fre, hin, mar, kna, tel, bho, ben, spa, rus, jpn, chi, zho, deu, heb, nld, guj, mai]
# ISO 639.2 standard: https://www.loc.gov/standards/iso639-2/php/code_list.php

# Timezone
timezone: Asia/Kolkata

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .parcel-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE
  - README.md
  - package.json
  - package-lock.json
  - .ruby-version
  - Pipfile.lock
  - Pipfile
  - venv
  - .python-version
  - jekyll-bhautiki.gemspec
  - docs/
  - Rakefile
  - run.sh

kramdown:
  syntax_highlighter: rouge
  # https://github.com/jneen/rouge
  syntax_highlighter_opts:
    css_class: highlight
    # default_lang: console
    # line_format: '%i  '
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
      wrap: true

# Compress/minify the generated css file.
sass:
  style: compressed

collections:
  pages:
    output: true

# Front Matter defaults.
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: _posts # an empty string here means all files in the project
      type: posts # types available: pages, posts, drafts and custom collections (plural)
    values:
      layout: post
      permalink: /post/:title
      toc: true
  -
    scope:
      path: _pages
      type: pages
    values:
      layout: page
      permalink: /:title

jekyll-archives:
  enabled: [year, tags, categories]
  layout: archive
  permalinks:
    year: '/archive/:year/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'
