# Using custom workflows for github pages.
# - Test automation
# - Test artifact generation
# - Do NOT upload artifact
name: Test Jekyll Site

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        # Affirm whether setup-ruby@v1 and checkout@v4 will
        #   pick the latest (v1.219.0 and v4.2.2 respectively).
        with:
          # ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 2 # Increment this number if you need to re-download cached gems
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Run Tests
        run: bash run.sh -it
        env:
          JEKYLL_ENV: test
      - name: Test SASS
        run: rake sass
